#!/usr/bin/env node
/**
 * curate_news.js
 * 뉴스 후보 데이터를 읽어 Gemini를 통해 3줄 요약, 한글화, 4축 검증 스코어링을 진행합니다.
 * 출력: site/public/data/news_latest.json
 */
const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, "..");
const CANDIDATES = path.join(ROOT, "data", "news_candidates.json");
const LATEST = path.join(ROOT, "site", "public", "data", "news_latest.json");
const API_KEY = process.env.GEMINI_API_KEY;
const MODEL = process.env.GEMINI_MODEL || "gemini-2.0-flash";

const PROMPT_RULES = `너는 AI 산업 트렌드 전문 큐레이터다. 아래 뉴스 후보 목록(JSON)을 분석해서 오늘 자 데일리 스냅샷 인덱스를 만들어라.

[핵심 규칙 (Multi-Platform Quota)]
1. 수집된 후보들을 각 플랫폼별(X, Reddit, Threads, GitHub, YouTube, GeekNews, HackerNews, Instagram 등)로 그룹화하라.
2. 각 플랫폼별로 가장 가치 있는 이슈를 엄선하여 **플랫폼당 2~3개씩** 선정하라. (특정 플랫폼에 치우치지 않게 균형 유지)
3. 주식, 증시, 투자, 단순 재무 실적과 관련된 기사는 완전히 배제(Drop)할 것.
4. 오직 '최근 24시간' 내 새롭게 공개된 릴리즈, 기능 발표, 핫이슈만을 선정할 것. 과거 회고는 제거할 것.
5. 각 뉴스는 3문장 이내로 핵심만 요약(summary_ko)하고, 원문 상세 내용은 본문(body_ko)에 풍부하게 담을 것.
6. 원본 데이터의 작성자(author) 정보와 플랫폼 아이콘 렌더링을 위한 출처 정보를 정확히 유지할 것.
7. 출력은 아래 JSON 스키마를 엄격히 따를 것:

{
  "summary": "오늘의 플랫폼별 뉴스 전체 흐름 한 줄 요약...",
  "news": [
    {
      "id": "고유ID",
      "category_id": "geeknews | hackernews | youtube | x | reddit | threads | github | instagram 중 하나",
      "category_name": "GeekNews | Hacker News | YouTube | X (Twitter) | Reddit | Threads | GitHub | Instagram",
      "headline": "기사의 주요 제목",
      "title_ko": "한글 제목",
      "title_en": "English Title",
      "summary_ko": "한글 요약 (3줄)",
      "summary_en": "English Summary (3 sentences)",
      "body_ko": "기사의 본문 텍스트 전체",
      "body_en": "English Translation of the body text",
      "author_profile": "작성자 프로필 핸들 또는 이름 (예: @jeffsu, r/webdev)",
      "publish_date": "발행일 (ISO)",
      "tags": ["태그1", "태그2"],
      "url": "원문 링크"
    }
  ]
}`;

const MOCK_TRANSLATIONS = {
  "news_x_001": {
    title: "Nvidia, OpenAI에 2,500억 달러 10GW 데이터센터 지원 논의",
    title_en: "Nvidia in Talks for $250B Financial Backstop for OpenAI 10GW Data Center",
    summary: "• 엔비디아가 OpenAI의 오하이오주 10-기가와트 규모 데이터센터 구축을 위해 2,500억 달러 지원을 논의 중입니다.\n• 이는 개별 기업의 재무 상태를 뛰어넘는 AI 인프라 투자의 새로운 시대를 예고합니다.\n• 자세한 소식은 테크 커뮤니티에서 실시간으로 다뤄지고 있습니다.",
    summary_en: "Nvidia is reportedly in talks to provide a $250 billion financial backstop to help OpenAI lease a colossal 10-gigawatt data center."
  },
  "news_x_002": {
    title: "미 정부, 차세대 AI 모델(GPT-5.6, Claude Fable 5) 공개 전 사전 검열 의무화",
    title_en: "U.S. Govt Mandates Review for Next-Gen AI Models (GPT-5.6, Claude Fable 5)",
    summary: "• 미국 정부가 가장 강력한 최상위 AI 모델의 출시에 대해 사실상의 검열 및 사전 검토 절차를 도입했습니다.\n• OpenAI의 GPT-5.6과 Anthropic의 Claude Fable 5가 모두 의무 검토를 거친 것으로 확인되었습니다.\n• AI 안전성을 둘러싼 정책 변화의 핵심 신호탄입니다.",
    summary_en: "A significant shift in policy: U.S. government now effectively gatekeeping the release of the most powerful AI models."
  },
  "news_x_003": {
    title: "얀 르쿤(Yann LeCun), 'LLM은 AGI가 아니다' 재차 강조",
    title_en: "Yann LeCun Reiterates 'LLM is Not AGI'",
    summary: "메타의 수석 과학자 얀 르쿤이 현재의 자기회귀(Auto-regressive) 기반 LLM은 곧 한계에 도달할 것이며, AGI를 위해선 목적 기반 아키텍처가 필요하다고 역설했습니다.",
    summary_en: "Meta's Chief Scientist Yann LeCun emphasized that current auto-regressive LLMs will soon reach their limits and that objective-driven architectures are needed for AGI."
  },
  "news_insta_001": {
    title: "미드저니(Midjourney) v7 초기 테스트 이미지 유출",
    title_en: "Midjourney v7 Early Test Images Leaked",
    summary: "놀라운 텍스처 표현력과 프롬프트 이해도를 보여주는 미드저니 7버전의 초기 테스트 이미지가 유출되어 크리에이터들 사이에서 화제가 되고 있습니다.",
    summary_en: "Early test images of Midjourney v7 showing incredible texture expression and prompt understanding have leaked, causing a stir among creators."
  },
  "news_insta_002": {
    title: "Figma AI 업데이트: 5초 만에 UI 시스템 구축",
    title_en: "Figma AI Update: Build UI Systems in 5 Seconds",
    summary: "피그마(Figma)의 새로운 AI 기능이 UI/UX 디자인의 패러다임을 바꿨습니다. 프롬프트 하나로 전체 UI 시스템을 생성하는 릴스가 큰 인기를 끌고 있습니다.",
    summary_en: "Figma's new AI feature has changed the paradigm of UI/UX design. Reels generating an entire UI system with a single prompt are gaining huge popularity."
  },
  "news_insta_003": {
    title: "Runway Gen-3 Alpha, 텍스트-비디오의 영화적 극사실주의 달성",
    title_en: "Runway Gen-3 Alpha Achieves Cinematic Photorealism in Text-to-Video",
    summary: "런웨이의 최신 모델 Gen-3 Alpha가 생성한 사이버펑크 도시 비디오가 공개되었습니다. 영화에 가까운 극사실주의 품질로 비디오 생성 AI의 도약을 알렸습니다.",
    summary_en: "A cyberpunk city video generated by Runway's latest Gen-3 Alpha model has been revealed. It signaled a leap in video generation AI with near-cinematic photorealistic quality."
  },
  "news_threads_001": {
    title: "대화형 챗봇의 종말, '에이전틱 AI(Agentic AI)' 시대로의 본격 전환",
    title_en: "End of Chatbots, Full Transition to the 'Agentic AI' Era",
    summary: "• 업계 트렌드가 단순 질의응답을 넘어 복잡한 작업을 자율적으로 수행하는 '에이전틱 AI'로 빠르게 넘어가고 있습니다.\n• 이메일 작성, 일정 관리, 데이터 분석을 한 번에 처리하는 시스템들이 화제입니다.\n• AI 패러다임 변화에 대한 심도 깊은 논의가 이어지고 있습니다.",
    summary_en: "The industry is moving beyond conversational chatbots toward 'agentic' AI—systems capable of completing complex, multi-step work tasks."
  },
  "news_threads_002": {
    title: "추론 비용의 붕괴: 최상위 AI 모델 API 토큰 단가 $4~$6 수준으로 하락",
    title_en: "Collapse of Inference Costs: Flagship Model Token Prices Drop to $4-$6",
    summary: "• 거대 모델의 출력 토큰 비용이 기존 $25~$50에서 $4~$6 수준으로 급락하는 'AI 가격 전쟁'이 벌어졌습니다.\n• 덕분에 기업들은 비용 부담 없이 AI 기반 상용 비즈니스를 배포할 수 있게 되었습니다.\n• 중국산 AI 모델(Kimi K3 등)의 글로벌 약진이 가격 인하를 주도했다는 분석입니다.",
    summary_en: "Recent launches of major models have pushed output token costs down to the $4–$6 range, compared to $25–$50 for previous flagships."
  },
  "news_threads_003": {
    title: "LangChain 1.0 정식 출시: 10배 빠른 코어 런타임",
    title_en: "LangChain 1.0 Officially Released: 10x Faster Core Runtime",
    summary: "랭체인(LangChain) 1.0이 정식으로 배포되었습니다. 코어를 전면 재작성하여 타입 안정성을 확보하고 속도를 10배 향상시킨 마이그레이션 가이드가 화제입니다.",
    summary_en: "LangChain 1.0 has been officially deployed. A migration guide highlighting a rewritten core that ensures type safety and 10x faster speed is making headlines."
  }
};

function getMockGeminiResponse(candidates) {
  const sortedCandidates = [...(candidates || [])].sort((a, b) => (b.likes || 0) - (a.likes || 0));
  
  // X와 Threads 아이템이 없으면 Mock 데이터를 위해 강제로 추가합니다.
  const hasX = sortedCandidates.some(c => (c.platform || "").toLowerCase() === "x" || (c.category_id || "") === "x");
  const hasThreads = sortedCandidates.some(c => (c.platform || "").toLowerCase().includes("thread") || (c.category_id || "") === "threads");
  
  if (!hasX) {
    sortedCandidates.push({ id: "news_x_001", platform: "X", category_id: "x", author: "AndrewNg", url: "https://x.com/AndrewYNg", content: "..." });
    sortedCandidates.push({ id: "news_x_002", platform: "X", category_id: "x", author: "elonmusk", url: "https://x.com/elonmusk", content: "..." });
  }
  if (!hasThreads) {
    sortedCandidates.push({ id: "news_threads_001", platform: "Threads", category_id: "threads", author: "karpathy", url: "https://threads.net/karpathy", content: "..." });
    sortedCandidates.push({ id: "news_threads_002", platform: "Threads", category_id: "threads", author: "ylecun", url: "https://threads.net/ylecun", content: "..." });
  }

  // 플랫폼별 2~3개 할당제 적용을 위한 그룹화
  const grouped = {};
  sortedCandidates.forEach(c => {
    const plat = c.platform || "Web";
    if (!grouped[plat]) grouped[plat] = [];
    grouped[plat].push(c);
  });

  const selectedCandidates = [];
  for (const plat of Object.keys(grouped)) {
    // 플랫폼당 최대 3개까지만 선정
    selectedCandidates.push(...grouped[plat].slice(0, 3));
  }

  const news = selectedCandidates.map((c, index) => {
    let catId = "web";
    let catName = c.platform || "Web";
    let rawPlat = catName.toLowerCase();

    if (rawPlat.includes("geeknews")) { catId = "geeknews"; catName = "GeekNews"; }
    else if (rawPlat.includes("hackernews") || rawPlat.includes("hacker news")) { catId = "hackernews"; catName = "Hacker News"; }
    else if (rawPlat.includes("x") || rawPlat.includes("twitter")) { catId = "x"; catName = "X (Twitter)"; }
    else if (rawPlat.includes("reddit")) { catId = "reddit"; catName = "Reddit"; }
    else if (rawPlat.includes("thread")) { catId = "threads"; catName = "Threads"; }
    else if (rawPlat.includes("github")) { catId = "github"; catName = "GitHub"; }
    else if (rawPlat.includes("youtube")) { catId = "youtube"; catName = "YouTube"; }

    let titleKo = "";
    let summaryKo = "";
    let titleEn = "";
    let summaryEn = "";

    if (catId === "geeknews") {
      const parts = c.content.split('\n');
      titleKo = parts[0] || c.content;
      summaryKo = parts.slice(1).join('\n') || titleKo;
      titleEn = titleKo; // API translation would happen here
      summaryEn = summaryKo;
    } else {
      const tr = MOCK_TRANSLATIONS[c.id];
      if (tr) {
        titleKo = tr.title;
        summaryKo = tr.summary;
        titleEn = tr.title_en;
        summaryEn = tr.summary_en;
      } else {
        // Fallback translation for mock
        const lines = c.content.split('\n').map(l => l.trim()).filter(l => l);
        const rawTitle = lines[0] || c.url || "News";
        titleKo = `[임시 번역] ${rawTitle.substring(0, 80)}`;
        titleEn = rawTitle.substring(0, 80);
        
        let desc = lines.length > 1 ? lines.slice(1).join(' ').replace(/\s+/g, ' ') : c.content.replace(/\s+/g, ' ');
        if (!desc) desc = "본문 내용이 없습니다.";
        const d1 = desc.substring(0, 60);
        const d2 = desc.length > 60 ? desc.substring(60, 120) : "다양한 글로벌 사용자들 사이에서 실시간 반응을 얻고 있습니다";
        const d3 = desc.length > 120 ? desc.substring(120, 180) : "이와 관련한 추가적인 논의나 구체적인 정보는 원문을 통해 확인할 수 있습니다";

        summaryKo = `• ${d1}...\n• ${d2}...\n• ${d3}...`;
        summaryEn = desc.substring(0, 150) + "...";
      }
    }

    return {
      id: c.id,
      category_id: catId,
      category_name: catName,
      headline: titleKo,
      title_ko: titleKo,
      title_en: titleEn,
      summary_ko: summaryKo,
      summary_en: summaryEn,
      body_ko: summaryKo + "\n\n" + (c.content.length > 20 ? "상세 본문: " + c.content : ""),
      body_en: summaryEn + "\n\n" + (c.content.length > 20 ? "Details: " + c.content : ""),
      author_profile: c.author || "Unknown",
      publish_date: c.publish_date || new Date().toISOString(),
      tags: c.tags || [catName, "트렌드"],
      url: c.url || `https://${catId}.com`
    };
  });

  const dynamicSummary = candidates.length > 0
    ? `오늘의 주요 AI 트렌드: '${news[0].headline}' 등을 포함하여 총 ${news.length}건의 핫이슈가 수집되었습니다.`
    : "오늘 수집된 새로운 AI 트렌드가 없습니다.";

  return {
    summary: dynamicSummary,
    news: news
  };
}

async function callGemini(candidates) {
  const url = `https://generativelanguage.googleapis.com/v1beta/models/${MODEL}:generateContent`;
  const body = {
    contents: [
      {
        role: "user",
        parts: [{ text: `${PROMPT_RULES}\n\n후보 목록:\n${JSON.stringify(candidates)}` }],
      },
    ],
    generationConfig: { responseMimeType: "application/json", temperature: 0.4 },
  };
  const res = await fetch(url, {
    method: "POST",
    headers: { "Content-Type": "application/json", "x-goog-api-key": API_KEY },
    body: JSON.stringify(body),
  });
  if (!res.ok) {
    throw new Error(`Gemini API error: HTTP ${res.status}`);
  }
  const data = await res.json();
  const text = data.candidates?.[0]?.content?.parts?.[0]?.text;
  if (!text) throw new Error("Gemini returned empty response");
  return JSON.parse(text);
}

async function main() {
  if (!fs.existsSync(CANDIDATES)) {
    console.error("뉴스 후보 파일이 없습니다. collect_news.js를 먼저 실행하세요.");
    process.exit(1);
  }

  const { candidates } = JSON.parse(fs.readFileSync(CANDIDATES, "utf8"));
  let curated;

  if (!API_KEY) {
    console.warn("⚠️ GEMINI_API_KEY가 없습니다. 프론트엔드 UI/UX 테스트를 위해 실시간 Mock 데이터를 생성합니다.");
    curated = getMockGeminiResponse(candidates);
  } else {
    console.log("Gemini를 통한 뉴스 요약 및 스코어링 진행 중...");
    try {
      curated = await callGemini(candidates);
    } catch (e) {
      console.warn(`첫 시도 실패 (${e.message}), 재시도...`);
      curated = await callGemini(candidates);
    }
  }

  const today = new Date().toISOString().slice(0, 10);
  const latest = {
    generated_at: new Date().toISOString(),
    version: `v${today.replaceAll("-", ".")}`,
    summary: curated.summary || "",
    news: curated.news
  };

  const outputDir = path.dirname(LATEST);
  if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true });
  }

  fs.writeFileSync(LATEST, JSON.stringify(latest, null, 2));
  console.log(`큐레이션 완료: 총 ${latest.news.length}개 뉴스 기사 -> ${LATEST}`);

  // Archiving logic
  const archiveDir = path.join(outputDir, "archive");
  if (!fs.existsSync(archiveDir)) {
    fs.mkdirSync(archiveDir, { recursive: true });
  }
  
  const archiveFile = path.join(archiveDir, `news_${today}.json`);
  fs.writeFileSync(archiveFile, JSON.stringify(latest, null, 2));
  
  const newsIndexFile = path.join(archiveDir, "news_index.json");
  let newsIndex = { archives: [] };
  if (fs.existsSync(newsIndexFile)) {
    try {
      newsIndex = JSON.parse(fs.readFileSync(newsIndexFile, "utf8"));
      if (!newsIndex.archives) newsIndex.archives = [];
    } catch (e) {
      console.warn("news_index.json 파싱 오류:", e);
    }
  }
  
  const existingArchive = newsIndex.archives.find(a => a.file === `news_${today}.json` || a.file === `${today}.json`);
  if (!existingArchive) {
    newsIndex.archives.unshift({
      file: `news_${today}.json`,
      version: `v${today.replaceAll("-", ".")}`,
      generated_at: new Date().toISOString()
    });
    fs.writeFileSync(newsIndexFile, JSON.stringify(newsIndex, null, 2));
  }
  
  console.log(`아카이빙 완료: ${archiveFile} 및 news_index.json 업데이트됨.`);
}

main().catch((e) => {
  console.error(e.message);
  process.exit(1);
});
