#!/usr/bin/env node
/**
 * curate_news.js
 * 뉴스 후보 데이터를 읽어 Gemini를 통해 3줄 요약, 한글화, 4축 검증 스코어링을 진행합니다.
 * 출력: site/public/data/news_latest.json
 */
const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, "..");
const CANDIDATES = path.join(ROOT, "data", "news_candidates.json");
const LATEST = path.join(ROOT, "site", "public", "data", "news_latest.json");
const API_KEY = process.env.GEMINI_API_KEY;
const MODEL = process.env.GEMINI_MODEL || "gemini-2.0-flash";

const PROMPT_RULES = `너는 AI 산업 트렌드 전문 큐레이터다. 아래 뉴스 후보 목록(JSON)을 분석해서 오늘 자 데일리 스냅샷 인덱스를 만들어라.

[핵심 규칙 (Single Pass Pipeline)]
1. 주식, 증시, 투자, 단순 재무 실적과 관련된 기사는 배열에서 완전히 배제(Drop)할 것.
2. 중복되는 주제의 기사는 가장 내용이 풍부한 1개만 남기고 나머지는 배제할 것.
3. [중요] 오직 '어제~오늘' 새롭게 공개된 릴리즈, 기능 발표, 핫이슈만을 선정할 것. 과거 회고나 뒷북 요약은 제거(Drop)할 것.
4. 위 조건을 충족하는 핵심 이슈들만 선별하여 가장 주목받는(핫한) 순서대로 정렬할 것. (최대 10개 내외로 압축하여 피로도를 줄일 것)
5. 각 뉴스는 3문장 이내로 핵심만 요약(summary_ko)하고, 원문 또는 상세 내용은 본문(body_ko)에 최대한 풍부하게 담을 것.
6. 출력은 아래 JSON 스키마를 엄격히 따를 것 (8가지 필수 필드 보장):

{
  "summary": "전체 뉴스 흐름 한 줄 요약 (예: 새로운 AI 개발 도구와 오픈소스 모델의 약진)...",
  "news": [
    {
      "id": "고유ID",
      "category_id": "geeknews | instagram | x | threads 중 하나",
      "category_name": "GeekNews | Instagram | X (Twitter) | Threads",
      "headline": "기사의 주요 제목 및 부제목",
      "title_ko": "한글 제목",
      "title_en": "English Title",
      "summary_ko": "한글 요약 (3줄)",
      "summary_en": "English Summary (3 sentences)",
      "body_ko": "기사의 본문 텍스트 전체",
      "body_en": "English Translation of the body text",
      "author": "콘텐츠를 작성한 작가 또는 기자 이름",
      "publish_date": "발행일 (ISO)",
      "tags": ["기술", "오픈소스", "개발자도구"],
      "multimedia": ["이미지 URL 등 시각적 요소 (영상 제외)"],
      "url": "원문 링크",
      "related_articles": [ {"title": "관련 기사 제목", "url": "링크"} ]
    }
  ]
}`;

const MOCK_TRANSLATIONS = {
  "news_x_001": {
    title: "GPT-4.5 아키텍처 구조 유출, 10T 파라미터 희소 MoE 모델 도입",
    title_en: "GPT-4.5 Architecture Leaked, Introduces 10T Parameter Sparse MoE Model",
    summary: "오픈AI의 GPT-4.5가 10조 개(10T)의 파라미터를 갖춘 희소 MoE 구조를 택했다는 소식이 유출되며 AI 개발자들 사이에서 큰 기대를 모으고 있습니다.",
    summary_en: "News leaked that OpenAI's GPT-4.5 adopted a sparse MoE architecture with 10 trillion (10T) parameters, raising great expectations among AI developers."
  },
  "news_x_002": {
    title: "일론 머스크, 그록(Grok) 2.0 배포 개시 선언",
    title_en: "Elon Musk Announces the Rollout of Grok 2.0",
    summary: "X(트위터)의 실시간 데이터를 무제한으로 학습한 검열 없는 Grok 2.0 모델이 배포를 시작했으며, 다수의 벤치마크에서 GPT-4를 능가한다는 소식입니다.",
    summary_en: "The uncensored Grok 2.0 model, which learned unlimited real-time data from X (Twitter), has begun rollout and is reported to outperform GPT-4 in multiple benchmarks."
  },
  "news_x_003": {
    title: "얀 르쿤(Yann LeCun), 'LLM은 AGI가 아니다' 재차 강조",
    title_en: "Yann LeCun Reiterates 'LLM is Not AGI'",
    summary: "메타의 수석 과학자 얀 르쿤이 현재의 자기회귀(Auto-regressive) 기반 LLM은 곧 한계에 도달할 것이며, AGI를 위해선 목적 기반 아키텍처가 필요하다고 역설했습니다.",
    summary_en: "Meta's Chief Scientist Yann LeCun emphasized that current auto-regressive LLMs will soon reach their limits and that objective-driven architectures are needed for AGI."
  },
  "news_insta_001": {
    title: "미드저니(Midjourney) v7 초기 테스트 이미지 유출",
    title_en: "Midjourney v7 Early Test Images Leaked",
    summary: "놀라운 텍스처 표현력과 프롬프트 이해도를 보여주는 미드저니 7버전의 초기 테스트 이미지가 유출되어 크리에이터들 사이에서 화제가 되고 있습니다.",
    summary_en: "Early test images of Midjourney v7 showing incredible texture expression and prompt understanding have leaked, causing a stir among creators."
  },
  "news_insta_002": {
    title: "Figma AI 업데이트: 5초 만에 UI 시스템 구축",
    title_en: "Figma AI Update: Build UI Systems in 5 Seconds",
    summary: "피그마(Figma)의 새로운 AI 기능이 UI/UX 디자인의 패러다임을 바꿨습니다. 프롬프트 하나로 전체 UI 시스템을 생성하는 릴스가 큰 인기를 끌고 있습니다.",
    summary_en: "Figma's new AI feature has changed the paradigm of UI/UX design. Reels generating an entire UI system with a single prompt are gaining huge popularity."
  },
  "news_insta_003": {
    title: "Runway Gen-3 Alpha, 텍스트-비디오의 영화적 극사실주의 달성",
    title_en: "Runway Gen-3 Alpha Achieves Cinematic Photorealism in Text-to-Video",
    summary: "런웨이의 최신 모델 Gen-3 Alpha가 생성한 사이버펑크 도시 비디오가 공개되었습니다. 영화에 가까운 극사실주의 품질로 비디오 생성 AI의 도약을 알렸습니다.",
    summary_en: "A cyberpunk city video generated by Runway's latest Gen-3 Alpha model has been revealed. It signaled a leap in video generation AI with near-cinematic photorealistic quality."
  },
  "news_threads_001": {
    title: "LLM 오케스트레이션의 복잡성과 '컴파운딩 시스템' 트렌드",
    title_en: "The Complexity of LLM Orchestration and the 'Compounding Systems' Trend",
    summary: "안드레이 카파시(Andrej Karpathy)가 스크래치부터 LLM을 구축하는 것은 쉬워졌으나 오케스트레이션이 복잡해졌으며, 이제는 복합 AI 시스템(Compounding AI)이 대세라고 평가했습니다.",
    summary_en: "Andrej Karpathy commented that while building LLMs from scratch has gotten easier, orchestration has become complex, and Compounding AI systems are now the main trend."
  },
  "news_threads_002": {
    title: "프롬프트 엔지니어링의 종말, '플로우(Flow) 엔지니어링' 부상",
    title_en: "The End of Prompt Engineering, the Rise of 'Flow Engineering'",
    summary: "2026 AI 엔지니어 서밋의 핵심 화두는 에이전트 구축 시 단순 프롬프팅이 아닌 '플로우(Flow) 엔지니어링'이 새로운 표준으로 자리잡았다는 점입니다.",
    summary_en: "The key topic of the 2026 AI Engineer Summit is that 'Flow Engineering' rather than simple prompting has become the new standard for building agents."
  },
  "news_threads_003": {
    title: "LangChain 1.0 정식 출시: 10배 빠른 코어 런타임",
    title_en: "LangChain 1.0 Officially Released: 10x Faster Core Runtime",
    summary: "랭체인(LangChain) 1.0이 정식으로 배포되었습니다. 코어를 전면 재작성하여 타입 안정성을 확보하고 속도를 10배 향상시킨 마이그레이션 가이드가 화제입니다.",
    summary_en: "LangChain 1.0 has been officially deployed. A migration guide highlighting a rewritten core that ensures type safety and 10x faster speed is making headlines."
  }
};

function getMockGeminiResponse(candidates) {
  const sortedCandidates = [...(candidates || [])].sort((a, b) => (b.likes || 0) - (a.likes || 0));
  const news = sortedCandidates.map(c => {
    let catId = "x";
    let catName = "X (Twitter)";
    if (c.platform === "GeekNews") { catId = "geeknews"; catName = "GeekNews"; }
    else if (c.platform === "Instagram") { catId = "instagram"; catName = "Instagram"; }
    else if (c.platform === "Threads") { catId = "threads"; catName = "Threads"; }

    let titleKo = "";
    let summaryKo = "";
    let titleEn = "";
    let summaryEn = "";

    if (c.platform === "GeekNews") {
      const parts = c.content.split('\n');
      titleKo = parts[0] || c.content;
      summaryKo = parts.slice(1).join('\n') || titleKo;
      titleEn = titleKo; // API translation would happen here
      summaryEn = summaryKo;
    } else {
      const tr = MOCK_TRANSLATIONS[c.id];
      if (tr) {
        titleKo = tr.title;
        summaryKo = tr.summary;
        titleEn = tr.title_en;
        summaryEn = tr.summary_en;
      } else {
        titleKo = c.content.slice(0, 60);
        summaryKo = c.content;
        titleEn = titleKo;
        summaryEn = summaryKo;
      }
    }

    return {
      id: c.id,
      category_id: catId,
      category_name: catName,
      headline: titleKo,
      title_ko: titleKo,
      title_en: titleEn,
      summary_ko: summaryKo,
      summary_en: summaryEn,
      body_ko: summaryKo + "\n" + (c.content.length > 20 ? "상세 본문: " + c.content : ""),
      body_en: summaryEn + "\n" + (c.content.length > 20 ? "Details: " + c.content : ""),
      author: c.author || "Unknown",
      publish_date: c.publish_date || new Date().toISOString(),
      tags: c.tags || [catName, "트렌드"],
      multimedia: c.multimedia || [],
      url: c.url,
      related_articles: c.related_articles || [],
      sources: c.references || [c.platform]
    };
  }); // 이전처럼 제한 없이 수집된 모든 기사(21개 등)를 반환하도록 복구

  const dynamicSummary = candidates.length > 0
    ? `오늘의 주요 AI 트렌드: '${news[0].headline}' 등을 포함하여 총 ${news.length}건의 핫이슈가 수집되었습니다.`
    : "오늘 수집된 새로운 AI 트렌드가 없습니다.";

  return {
    summary: dynamicSummary,
    news: news
  };
}

async function callGemini(candidates) {
  const url = `https://generativelanguage.googleapis.com/v1beta/models/${MODEL}:generateContent`;
  const body = {
    contents: [
      {
        role: "user",
        parts: [{ text: `${PROMPT_RULES}\n\n후보 목록:\n${JSON.stringify(candidates)}` }],
      },
    ],
    generationConfig: { responseMimeType: "application/json", temperature: 0.4 },
  };
  const res = await fetch(url, {
    method: "POST",
    headers: { "Content-Type": "application/json", "x-goog-api-key": API_KEY },
    body: JSON.stringify(body),
  });
  if (!res.ok) {
    throw new Error(`Gemini API error: HTTP ${res.status}`);
  }
  const data = await res.json();
  const text = data.candidates?.[0]?.content?.parts?.[0]?.text;
  if (!text) throw new Error("Gemini returned empty response");
  return JSON.parse(text);
}

async function main() {
  if (!fs.existsSync(CANDIDATES)) {
    console.error("뉴스 후보 파일이 없습니다. collect_news.js를 먼저 실행하세요.");
    process.exit(1);
  }

  const { candidates } = JSON.parse(fs.readFileSync(CANDIDATES, "utf8"));
  let curated;

  if (!API_KEY) {
    console.warn("⚠️ GEMINI_API_KEY가 없습니다. 프론트엔드 UI/UX 테스트를 위해 실시간 Mock 데이터를 생성합니다.");
    curated = getMockGeminiResponse(candidates);
  } else {
    console.log("Gemini를 통한 뉴스 요약 및 스코어링 진행 중...");
    try {
      curated = await callGemini(candidates);
    } catch (e) {
      console.warn(`첫 시도 실패 (${e.message}), 재시도...`);
      curated = await callGemini(candidates);
    }
  }

  const today = new Date().toISOString().slice(0, 10);
  const latest = {
    generated_at: new Date().toISOString(),
    version: `v${today.replaceAll("-", ".")}`,
    summary: curated.summary || "",
    news: curated.news
  };

  const outputDir = path.dirname(LATEST);
  if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true });
  }

  fs.writeFileSync(LATEST, JSON.stringify(latest, null, 2));
  console.log(`큐레이션 완료: 총 ${latest.news.length}개 뉴스 기사 -> ${LATEST}`);

  // Archiving logic
  const archiveDir = path.join(outputDir, "archive");
  if (!fs.existsSync(archiveDir)) {
    fs.mkdirSync(archiveDir, { recursive: true });
  }
  
  const archiveFile = path.join(archiveDir, `news_${today}.json`);
  fs.writeFileSync(archiveFile, JSON.stringify(latest, null, 2));
  
  const newsIndexFile = path.join(archiveDir, "news_index.json");
  let newsIndex = { archives: [] };
  if (fs.existsSync(newsIndexFile)) {
    try {
      newsIndex = JSON.parse(fs.readFileSync(newsIndexFile, "utf8"));
      if (!newsIndex.archives) newsIndex.archives = [];
    } catch (e) {
      console.warn("news_index.json 파싱 오류:", e);
    }
  }
  
  const existingArchive = newsIndex.archives.find(a => a.file === `news_${today}.json` || a.file === `${today}.json`);
  if (!existingArchive) {
    newsIndex.archives.unshift({
      file: `news_${today}.json`,
      version: `v${today.replaceAll("-", ".")}`,
      generated_at: new Date().toISOString()
    });
    fs.writeFileSync(newsIndexFile, JSON.stringify(newsIndex, null, 2));
  }
  
  console.log(`아카이빙 완료: ${archiveFile} 및 news_index.json 업데이트됨.`);
}

main().catch((e) => {
  console.error(e.message);
  process.exit(1);
});
